### PR TITLE
Fix compilation issues in MacOS

### PR DESCRIPTION
**Pull request by DAddYE**
This should fix compilation issues with MacOS 10.13.6

### CODE REVIEW

**Comment by rpasichnyk** [comment]
I have no issues compiling. What version of XCode do you use? And what version of Qt?

**Comment by DAddYE** [comment]
- qt: stable 5.11.2 (bottled)
- XCode for 10.13.6

**Comment by leonvuksic** [comment]
Hey rpasichnyk! Happy NYE! Can you please put up the latest release of the tool for Mac? I don't know how to compile etc.. thank you!

**Comment by rpasichnyk** [comment]
Done

**Comment by maturing** [comment]
Hey rpasichnyk. Just opened ur great program, u should turn off dark mode option, it's very hard to see and very uncomfortable switching between VESC settings, some of them in light mode and some in dark. Thank you, great work, keep it up👍

**Pull request closed without merging**
